# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_fastsdid_wrappers", use_symbols = TRUE, package_name = "fastsdid")

#' @docType package
#' @usage NULL
#' @useDynLib fastsdid, .registration = TRUE
NULL

fw_sc_weight <- function(xy, w, fit_intercept, eta, min_decrease, max_iter) .Call(wrap__fw_sc_weight, xy, w, fit_intercept, eta, min_decrease, max_iter)

fw_sc_weight_covariates <- function(xty, cov, beta, lambda, eta_lambda, fit_intercept_lambda, update_lambda, omega, eta_omega, fit_intercept_omega, update_omega, min_decrease, max_iter) .Call(wrap__fw_sc_weight_covariates, xty, cov, beta, lambda, eta_lambda, fit_intercept_lambda, update_lambda, omega, eta_omega, fit_intercept_omega, update_omega, min_decrease, max_iter)


# nolint end
